import {parseRotiFile} from './parser.js';
import {getGrid} from './rotiGrid.js';
import {computeStatistics,computeSectorSummary} from './statistics.js';
import {detectOvalProxy} from './ovalProxy.js';
import {renderPolarMap,getScaleMax,hitTest} from './renderMap.js';
import {exportJson,exportCellsCsv,exportOvalCsv,saveCanvasPng,saveReportPng} from './exporters.js';
import {downloadBlob,round} from './utils.js';

const $=id=>document.getElementById(id);const canvas=$('mapCanvas');let geom=null;
const state={parsed:null,grid:null,stats:null,sectors:null,oval:null,warnings:[],settings:{scaleMode:'igs',threshold:.5,method:'hybrid',smoothing:'light'}};
function threshold(){return $('thresholdSelect').value==='custom'?Number($('customThreshold').value):Number($('thresholdSelect').value)}
async function readFile(file){const bytes=new Uint8Array(await file.arrayBuffer());if(/\.gz$/i.test(file.name)){return await new Promise((resolve,reject)=>{window.fflate.gunzipAsync(bytes,(err,out)=>err?reject(err):resolve(new TextDecoder().decode(out)))})}return new TextDecoder().decode(bytes)}
function refresh(){if(!state.grid){renderEmpty();return}state.settings={scaleMode:$('scaleSelect').value,threshold:threshold(),method:$('methodSelect').value,smoothing:$('smoothSelect').value};state.stats=computeStatistics(state.grid,state.settings.threshold);state.sectors=computeSectorSummary(state.grid);const scaleMax=getScaleMax(state.grid,state.settings.scaleMode,state.stats);state.oval=detectOvalProxy(state.grid,{method:state.settings.method,threshold:state.settings.threshold,smoothing:state.settings.smoothing});state.warnings=[...(state.parsed?.warnings||[]),...state.oval.warnings];geom=renderPolarMap(canvas,state.grid,{threshold:state.settings.threshold,scaleMax,oval:state.oval});renderPanels();}
function renderEmpty(){const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#08111f';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#d9efff';ctx.font='28px sans-serif';ctx.fillText('Load an IGS-style ROTI .INX or .INX.gz file',70,120);ctx.fillStyle='#8fb0ca';ctx.font='18px sans-serif';ctx.fillText('Processing stays local in your browser. The sample files are available in /samples.',70,158)}
function kv(el,obj){el.innerHTML='';for(const [k,v] of Object.entries(obj)){el.insertAdjacentHTML('beforeend',`<span>${k}</span><strong>${v??'—'}</strong>`)}}
function renderPanels(){const m=state.parsed.metadata;kv($('metadataGrid'),{'Product':m.productName,'Date':m.date,'Year / DOY':`${m.year??'—'} / ${m.doy??'—'}`,'Input extension':m.inputExtension||'content-detected','Grid size':m.gridSize,'Section':m.section,'Coordinates':m.coordinateSystem});kv($('statsGrid'),{'Min':state.stats.min,'Max':state.stats.max,'Mean':state.stats.mean,'Median':state.stats.median,'p90':state.stats.p90,'p95':state.stats.p95,'p99':state.stats.p99,'Active cells':state.stats.activeCells,'% active':`${state.stats.activePercent}%`});$('sectorSummary').innerHTML=state.sectors.map(s=>`<div class="sector"><b>${s.name}</b><span>${s.mean}</span><div class="bar"><i style="width:${Math.min(100,s.mean/(state.stats.p99||1)*100)}%"></i></div></div>`).join('');kv($('ovalSummary'),{'Method':state.oval.settings.method,'Threshold':state.oval.settings.threshold,'Smoothing':state.oval.settings.smoothing,'Detected sectors':`${state.oval.detectedSectors} / ${state.grid.mltBins}`,'Mean confidence':round(state.oval.raw.reduce((a,b)=>a+(b.confidence||0),0)/state.oval.raw.length,2)});$('warnings').innerHTML=state.warnings.map(w=>`<div class="warning">${w}</div>`).join('')}
async function onFile(file){$('fileName').textContent=file.name;try{const text=await readFile(file);state.parsed=parseRotiFile(text,file.name);state.grid=getGrid(state.parsed,$('sectionSelect').value);refresh()}catch(e){state.parsed=null;state.grid=null;$('warnings').innerHTML=`<div class="warning">${e.message}</div>`;renderEmpty()}}
$('fileInput').addEventListener('change',e=>{const f=e.target.files[0];if(f)onFile(f)});['scaleSelect','thresholdSelect','customThreshold','methodSelect','smoothSelect','sectionSelect'].forEach(id=>$(id).addEventListener('change',()=>{$('customThreshold').hidden=$('thresholdSelect').value!=='custom';if(state.parsed){state.grid=getGrid(state.parsed,$('sectionSelect').value);refresh()}}));
canvas.addEventListener('mousemove',e=>{if(!state.grid||!geom)return;const h=hitTest(canvas,state.grid,e.clientX,e.clientY,geom);const tip=$('tooltip');if(!h){tip.hidden=true;return}tip.hidden=false;tip.style.left=`${e.offsetX+14}px`;tip.style.top=`${e.offsetY+14}px`;tip.innerHTML=`<b>MLAT</b> ${h.mlat.toFixed(1)}°<br><b>MLT</b> ${h.mltHour.toFixed(2)} h<br><b>ROTI</b> ${h.roti.toFixed(4)}<br>${h.roti>=state.settings.threshold?'active':'inactive'}`});canvas.addEventListener('mouseleave',()=>$('tooltip').hidden=true);
function base(){return (state.parsed?.metadata.fileName||'roti-map').replace(/\.(gz|INX|inx|f)$/g,'')}
$('savePngBtn').onclick=$('saveMapBtn').onclick=()=>state.grid&&saveCanvasPng(canvas,`${base()}_map.png`);$('saveReportBtn').onclick=()=>state.grid&&saveReportPng(canvas,state,`${base()}_report.png`);$('jsonBtn').onclick=()=>state.grid&&downloadBlob(exportJson(state),`${base()}_statistics.json`,'application/json');$('cellsBtn').onclick=()=>state.grid&&downloadBlob(exportCellsCsv(state.grid,state.parsed.metadata),`${base()}_cells.csv`,'text/csv');$('ovalBtn').onclick=()=>state.grid&&downloadBlob(exportOvalCsv(state.oval,state.parsed.metadata),`${base()}_oval.csv`,'text/csv');$('exportBundleBtn').onclick=()=>{if(!state.grid)return;$('jsonBtn').click();$('cellsBtn').click();$('ovalBtn').click()};$('aboutBtn').onclick=()=>$('aboutDialog').showModal();document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>$('aboutDialog').showModal());window.addEventListener('resize',refresh);renderEmpty();
