import {clamp} from './utils.js';
import {mlatExtent} from './rotiGrid.js';
const palette=[[8,20,48],[20,92,160],[40,185,210],[110,220,110],[255,226,82],[255,132,64],[230,55,85]];
export const OVERLAY_OPACITY=.18;
function lerp(a,b,t){return a+(b-a)*t}function color(t){t=clamp(t,0,1);const x=t*(palette.length-1);const i=Math.floor(x);const f=x-i;const a=palette[i],b=palette[Math.min(i+1,palette.length-1)];return`rgb(${lerp(a[0],b[0],f)|0},${lerp(a[1],b[1],f)|0},${lerp(a[2],b[2],f)|0})`}
function css(name,fallback){return getComputedStyle(document.documentElement).getPropertyValue(name).trim()||fallback}
function theme(){return{mapBg:css('--map-bg','#08111f'),grid:css('--map-grid','#ffffff2b'),label:css('--map-label','#eef8ff'),muted:css('--map-muted','#9fb6cb'),colorbarBorder:css('--map-colorbar-border','#dfeeff'),ridge:css('--oval-ridge','#ffe86a'),boundary:css('--oval-boundary','#eaf7ff'),fill:css('--oval-fill','#67d8ff')}}
export function getScaleMax(grid,mode,stats){if(mode==='extended')return 2;if(mode==='adaptive')return Math.max(.1,stats?.p99||1);return 1}
export function polarGeometry(canvas,grid){const w=canvas.width,h=canvas.height,dpr=window.devicePixelRatio||1;const labelSpace=86*dpr,colorbarSpace=170*dpr,bottomNote=36*dpr,topPad=34*dpr,leftPad=54*dpr;const availableWidth=Math.max(240*dpr,w-leftPad-colorbarSpace-labelSpace*.35);const availableHeight=Math.max(240*dpr,h-topPad-bottomNote-labelSpace);const rMax=Math.max(100*dpr,Math.min(availableWidth/2,availableHeight/2));const cx=leftPad+labelSpace*.35+rMax;const cy=topPad+labelSpace/2+rMax;const {min}=mlatExtent(grid);return{w,h,dpr,cx,cy,rMax,minLat:min,maxLat:90,latSpan:90-min,labelSpace,colorbarSpace,bottomNote,availableWidth,availableHeight,plotBox:{left:cx-rMax,top:cy-rMax,right:cx+rMax,bottom:cy+rMax}}}
export function latToRadius(lat,g){return (90-lat)/g.latSpan*g.rMax}export function mltToAngle(hour){return (hour-12)/24*2*Math.PI-Math.PI/2}
function point(lat,h,g){const r=latToRadius(lat,g),a=mltToAngle(h);return{x:g.cx+r*Math.cos(a),y:g.cy+r*Math.sin(a)}}
function drawSegmentedLine(ctx,sectors,key,g,style){ctx.save();ctx.strokeStyle=style.color;ctx.lineWidth=style.width;ctx.lineCap='round';ctx.lineJoin='round';let prev=null;for(const s of sectors){const lat=s[key];if(!Number.isFinite(lat)){prev=null;continue}const p=point(lat,s.mltHour,g);if(prev){ctx.globalAlpha=(s.uncertain||prev.s.uncertain)?style.lowAlpha:style.alpha;ctx.setLineDash((s.uncertain||prev.s.uncertain)?style.lowDash:style.dash);ctx.beginPath();ctx.moveTo(prev.p.x,prev.p.y);ctx.lineTo(p.x,p.y);ctx.stroke()}prev={p,s}}ctx.restore()}
function drawProxyFill(ctx,sectors,g,t){const ready=sectors.filter(s=>Number.isFinite(s.equatorwardMlat)&&Number.isFinite(s.polewardMlat));if(ready.length<3)return;ctx.save();ctx.globalAlpha=OVERLAY_OPACITY;ctx.fillStyle=t.fill;ctx.beginPath();let first=true;for(const s of sectors){if(Number.isFinite(s.equatorwardMlat)){const p=point(s.equatorwardMlat,s.mltHour,g);if(first){ctx.moveTo(p.x,p.y);first=false}else ctx.lineTo(p.x,p.y)}}for(const s of [...sectors].reverse()){if(Number.isFinite(s.polewardMlat)){const p=point(s.polewardMlat,s.mltHour,g);ctx.lineTo(p.x,p.y)}}ctx.closePath();ctx.fill();ctx.restore()}
export function renderPolarMap(canvas,grid,settings={}){const ctx=canvas.getContext('2d');const dpr=window.devicePixelRatio||1;const rect=canvas.getBoundingClientRect();if(rect.width&&(Math.abs(canvas.width-rect.width*dpr)>5||Math.abs(canvas.height-rect.height*dpr)>5)){canvas.width=rect.width*dpr;canvas.height=rect.height*dpr}const t=theme();ctx.clearRect(0,0,canvas.width,canvas.height);const g=polarGeometry(canvas,grid);ctx.fillStyle=t.mapBg;ctx.fillRect(0,0,g.w,g.h);const maxScale=settings.scaleMax||1;const latStep=Math.abs(grid.rows[0]?.mlat-grid.rows[1]?.mlat)||2;for(const row of grid.rows){const inner=latToRadius(row.mlat+latStep/2,g);const outer=latToRadius(row.mlat-latStep/2,g);for(let j=0;j<row.values.length;j++){const h0=j*grid.mltStepHours,h1=(j+1)*grid.mltStepHours;ctx.beginPath();ctx.arc(g.cx,g.cy,outer,mltToAngle(h0),mltToAngle(h1));ctx.arc(g.cx,g.cy,Math.max(0,inner),mltToAngle(h1),mltToAngle(h0),true);ctx.closePath();ctx.fillStyle=color(row.values[j]/maxScale);ctx.fill();}}
 if(settings.showActive!==false){ctx.save();ctx.globalAlpha=.1;ctx.fillStyle='#ffffff';for(const row of grid.rows){for(let j=0;j<row.values.length;j++)if(row.values[j]>=settings.threshold){const inner=latToRadius(row.mlat+latStep/2,g),outer=latToRadius(row.mlat-latStep/2,g);ctx.beginPath();ctx.arc(g.cx,g.cy,outer,mltToAngle(j*grid.mltStepHours),mltToAngle((j+1)*grid.mltStepHours));ctx.arc(g.cx,g.cy,Math.max(0,inner),mltToAngle((j+1)*grid.mltStepHours),mltToAngle(j*grid.mltStepHours),true);ctx.fill();}}ctx.restore()}
 ctx.strokeStyle=t.grid;ctx.lineWidth=1.2*dpr;ctx.font=`${12*dpr}px sans-serif`;[50,60,70,80].forEach(lat=>{const r=latToRadius(lat,g);ctx.beginPath();ctx.arc(g.cx,g.cy,r,0,Math.PI*2);ctx.stroke();ctx.fillStyle=t.muted;ctx.fillText(`${lat}°`,g.cx+r+8*dpr,g.cy-4*dpr)});ctx.beginPath();ctx.arc(g.cx,g.cy,Math.max(0,latToRadius(90,g)),0,Math.PI*2);ctx.stroke();for(let h=0;h<24;h+=3){const a=mltToAngle(h);ctx.beginPath();ctx.moveTo(g.cx,g.cy);ctx.lineTo(g.cx+g.rMax*Math.cos(a),g.cy+g.rMax*Math.sin(a));ctx.stroke()}
 ctx.fillStyle=t.label;ctx.font=`${15*dpr}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';[['12 noon',12,0,-26],['06 dawn',6,50,0],['00 midnight',0,0,34],['18 dusk',18,-54,0]].forEach(([txt,h,dx,dy])=>{const p=point(g.minLat,h,g);ctx.fillText(txt,p.x+dx*dpr,p.y+dy*dpr)});ctx.textAlign='start';ctx.textBaseline='alphabetic';
 if(settings.showOval!==false&&settings.oval?.sectors?.length){const sectors=settings.oval.sectors;drawProxyFill(ctx,sectors,g,t);drawSegmentedLine(ctx,sectors,'equatorwardMlat',g,{color:t.boundary,width:2.2*dpr,dash:[8*dpr,5*dpr],lowDash:[2*dpr,5*dpr],alpha:.92,lowAlpha:.45});drawSegmentedLine(ctx,sectors,'polewardMlat',g,{color:t.boundary,width:2.2*dpr,dash:[8*dpr,5*dpr],lowDash:[2*dpr,5*dpr],alpha:.92,lowAlpha:.45});drawSegmentedLine(ctx,sectors,'ridgeMlat',g,{color:t.ridge,width:3*dpr,dash:[],lowDash:[4*dpr,5*dpr],alpha:.98,lowAlpha:.58});}
 drawColorbar(ctx,g,maxScale,dpr,t);ctx.fillStyle=t.muted;ctx.font=`${12*dpr}px sans-serif`;ctx.fillText('Corrected magnetic latitude / magnetic local time',20*dpr,(g.h-18*dpr));return g;}
function drawColorbar(ctx,g,maxScale,dpr,t){const x=g.w-g.colorbarSpace+42*dpr,y=Math.max(54*dpr,g.cy-g.rMax*.55),w=18*dpr,h=Math.min(g.rMax*1.1,g.h-y-58*dpr);for(let i=0;i<h;i++){ctx.fillStyle=color(1-i/h);ctx.fillRect(x,y+i,w,1)}ctx.strokeStyle=t.colorbarBorder;ctx.strokeRect(x,y,w,h);ctx.fillStyle=t.label;ctx.font=`${12*dpr}px sans-serif`;ctx.textAlign='left';for(let k=0;k<=4;k++){const v=maxScale*k/4;const yy=y+h-(h*k/4);ctx.beginPath();ctx.moveTo(x+w,yy);ctx.lineTo(x+w+5*dpr,yy);ctx.stroke();ctx.fillText(v.toFixed(maxScale>1?1:2),x+w+12*dpr,yy+4*dpr)}ctx.save();ctx.translate(x+82*dpr,y+h/2);ctx.rotate(-Math.PI/2);ctx.textAlign='center';ctx.fillText('ROTI [TECU/min]',0,0);ctx.restore()}
export function hitTest(canvas,grid,clientX,clientY,geom){const rect=canvas.getBoundingClientRect();const sx=canvas.width/rect.width,sy=canvas.height/rect.height;const x=(clientX-rect.left)*sx,y=(clientY-rect.top)*sy;const dx=x-geom.cx,dy=y-geom.cy;const r=Math.hypot(dx,dy);if(r>geom.rMax)return null;const lat=90-r/geom.rMax*geom.latSpan;let a=Math.atan2(dy,dx)+Math.PI/2;let h=((a/(2*Math.PI))*24+12+24)%24;const j=Math.floor(h/grid.mltStepHours)%grid.mltBins;let best=0,bd=Infinity;grid.rows.forEach((row,i)=>{const d=Math.abs(row.mlat-lat);if(d<bd){bd=d;best=i}});return{mlat:grid.rows[best].mlat,mltHour:j*grid.mltStepHours,roti:grid.rows[best].values[j]}}
