import {clamp} from './utils.js';
import {mlatExtent} from './rotiGrid.js';
const palette=[[8,20,48],[20,92,160],[40,185,210],[110,220,110],[255,226,82],[255,132,64],[230,55,85]];
function lerp(a,b,t){return a+(b-a)*t}function color(t){t=clamp(t,0,1);const x=t*(palette.length-1);const i=Math.floor(x);const f=x-i;const a=palette[i],b=palette[Math.min(i+1,palette.length-1)];return`rgb(${lerp(a[0],b[0],f)|0},${lerp(a[1],b[1],f)|0},${lerp(a[2],b[2],f)|0})`}
export function getScaleMax(grid,mode,stats){if(mode==='extended')return 2;if(mode==='adaptive')return Math.max(.1,stats?.p99||1);return 1}
export function polarGeometry(canvas,grid){const w=canvas.width,h=canvas.height;const cx=w*.45,cy=h*.50;const rMax=Math.min(w*.40,h*.43);const {min,max}=mlatExtent(grid);return{w,h,cx,cy,rMax,minLat:min,maxLat:90,latSpan:90-min}}
export function latToRadius(lat,g){return (90-lat)/g.latSpan*g.rMax}export function mltToAngle(hour){return (hour-12)/24*2*Math.PI-Math.PI/2}
function point(lat,h,g){const r=latToRadius(lat,g),a=mltToAngle(h);return{x:g.cx+r*Math.cos(a),y:g.cy+r*Math.sin(a)}}
function drawLine(ctx,pts,style={}){ctx.save();ctx.strokeStyle=style.color||'#fff';ctx.lineWidth=style.width||2;ctx.globalAlpha=style.alpha??1;if(style.dash)ctx.setLineDash(style.dash);ctx.beginPath();let started=false;for(const p of pts){if(!Number.isFinite(p.lat)){started=false;continue}const xy=point(p.lat,p.h,gCurrent);if(!started){ctx.moveTo(xy.x,xy.y);started=true}else ctx.lineTo(xy.x,xy.y)}ctx.stroke();ctx.restore()}let gCurrent;
export function renderPolarMap(canvas,grid,settings={}){const ctx=canvas.getContext('2d');const dpr=window.devicePixelRatio||1;const rect=canvas.getBoundingClientRect();if(rect.width&&Math.abs(canvas.width-rect.width*dpr)>5){canvas.width=rect.width*dpr;canvas.height=rect.height*dpr}ctx.clearRect(0,0,canvas.width,canvas.height);const g=polarGeometry(canvas,grid);gCurrent=g;ctx.fillStyle='#08111f';ctx.fillRect(0,0,g.w,g.h);const maxScale=settings.scaleMax||1;const latStep=Math.abs(grid.rows[0]?.mlat-grid.rows[1]?.mlat)||2;for(const row of grid.rows){const inner=latToRadius(row.mlat+latStep/2,g);const outer=latToRadius(row.mlat-latStep/2,g);for(let j=0;j<row.values.length;j++){const h0=j*grid.mltStepHours,h1=(j+1)*grid.mltStepHours;ctx.beginPath();ctx.arc(g.cx,g.cy,outer,mltToAngle(h0),mltToAngle(h1));ctx.arc(g.cx,g.cy,Math.max(0,inner),mltToAngle(h1),mltToAngle(h0),true);ctx.closePath();ctx.fillStyle=color(row.values[j]/maxScale);ctx.fill();}}
 // Active threshold overlay emphasizes ROTI cells used by proxy methods.
 if(settings.showActive!==false){ctx.save();ctx.globalAlpha=.13;ctx.fillStyle='#ffffff';for(const row of grid.rows){for(let j=0;j<row.values.length;j++)if(row.values[j]>=settings.threshold){const inner=latToRadius(row.mlat+latStep/2,g),outer=latToRadius(row.mlat-latStep/2,g);ctx.beginPath();ctx.arc(g.cx,g.cy,outer,mltToAngle(j*grid.mltStepHours),mltToAngle((j+1)*grid.mltStepHours));ctx.arc(g.cx,g.cy,Math.max(0,inner),mltToAngle((j+1)*grid.mltStepHours),mltToAngle(j*grid.mltStepHours),true);ctx.fill();}}ctx.restore()}
 ctx.strokeStyle='#ffffff2b';ctx.lineWidth=1.2;[50,60,70,80,90].forEach(lat=>{const r=latToRadius(lat,g);ctx.beginPath();ctx.arc(g.cx,g.cy,r,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#c8d8e8';ctx.font=`${12*dpr}px sans-serif`;ctx.fillText(`${lat}°`,g.cx+r+5*dpr,g.cy-3*dpr)});for(let h=0;h<24;h+=3){const a=mltToAngle(h);ctx.beginPath();ctx.moveTo(g.cx,g.cy);ctx.lineTo(g.cx+g.rMax*Math.cos(a),g.cy+g.rMax*Math.sin(a));ctx.stroke()}ctx.fillStyle='#eef8ff';ctx.font=`${15*dpr}px sans-serif`;[['12 noon',12,0,-14],['06 dawn',6,18,4],['00 midnight',0,-42,28],['18 dusk',18,-78,4]].forEach(([txt,h,dx,dy])=>{const p=point(g.minLat,h,g);ctx.fillText(txt,p.x+dx*dpr,p.y+dy*dpr)});
 if(settings.oval?.sectors?.length){const sectors=settings.oval.sectors;const make=(key)=>sectors.map(s=>({h:s.mltHour,lat:s[key]}));ctx.save();ctx.globalAlpha=.26;ctx.fillStyle='#67d8ff';ctx.beginPath();let first=true;for(const s of sectors){if(Number.isFinite(s.equatorwardMlat)){const p=point(s.equatorwardMlat,s.mltHour,g);if(first){ctx.moveTo(p.x,p.y);first=false}else ctx.lineTo(p.x,p.y)}}for(const s of [...sectors].reverse()){if(Number.isFinite(s.polewardMlat)){const p=point(s.polewardMlat,s.mltHour,g);ctx.lineTo(p.x,p.y)}}ctx.closePath();ctx.fill();ctx.restore();drawLine(ctx,make('equatorwardMlat'),{color:'#eaf7ff',width:2*dpr,dash:[7*dpr,5*dpr],alpha:.9});drawLine(ctx,make('polewardMlat'),{color:'#eaf7ff',width:2*dpr,dash:[7*dpr,5*dpr],alpha:.9});drawLine(ctx,make('ridgeMlat'),{color:'#ffe86a',width:2.5*dpr,alpha:.95});}
 drawColorbar(ctx,g,maxScale,dpr);ctx.fillStyle='#9fb6cb';ctx.font=`${12*dpr}px sans-serif`;ctx.fillText('Corrected magnetic latitude / magnetic local time',20*dpr,(g.h-22*dpr));return g;}
function drawColorbar(ctx,g,maxScale,dpr){const x=g.w-92*dpr,y=g.h*.22,w=18*dpr,h=g.h*.50;for(let i=0;i<h;i++){ctx.fillStyle=color(1-i/h);ctx.fillRect(x,y+i,w,1)}ctx.strokeStyle='#dfeeff';ctx.strokeRect(x,y,w,h);ctx.fillStyle='#e8f7ff';ctx.font=`${12*dpr}px sans-serif`;ctx.save();ctx.translate(x+44*dpr,y+h/2);ctx.rotate(-Math.PI/2);ctx.fillText('ROTI [TECU/min]',-52*dpr,0);ctx.restore();for(let k=0;k<=4;k++){const v=maxScale*k/4;const yy=y+h-(h*k/4);ctx.fillText(v.toFixed(maxScale>1?1:2),x+25*dpr,yy+4*dpr)}}
export function hitTest(canvas,grid,clientX,clientY,geom){const rect=canvas.getBoundingClientRect();const sx=canvas.width/rect.width,sy=canvas.height/rect.height;const x=(clientX-rect.left)*sx,y=(clientY-rect.top)*sy;const dx=x-geom.cx,dy=y-geom.cy;const r=Math.hypot(dx,dy);if(r>geom.rMax)return null;const lat=90-r/geom.rMax*geom.latSpan;let a=Math.atan2(dy,dx)+Math.PI/2;let h=((a/(2*Math.PI))*24+12+24)%24;const j=Math.floor(h/grid.mltStepHours)%grid.mltBins;let best=0,bd=Infinity;grid.rows.forEach((row,i)=>{const d=Math.abs(row.mlat-lat);if(d<bd){bd=d;best=i}});return{mlat:grid.rows[best].mlat,mltHour:j*grid.mltStepHours,roti:grid.rows[best].values[j]}}
