export const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
export const round=(v,d=2)=>Number.isFinite(v)?Number(v.toFixed(d)):null;
export function doyToDate(year,doy){const d=new Date(Date.UTC(year,0,doy));return d.toISOString().slice(0,10)}
export function parseFilenameDate(fileName=''){let m=fileName.match(/_(\d{4})(\d{3})\d{4}_/);if(m)return{year:+m[1],doy:+m[2],date:doyToDate(+m[1],+m[2])};m=fileName.match(/roti(\d{3})0\.(\d{2})f/i);if(m){const yy=+m[2];const y=yy>=80?1900+yy:2000+yy;return{year:y,doy:+m[1],date:doyToDate(y,+m[1])}}return{};}
export function downloadBlob(content,name,type){const blob=content instanceof Blob?content:new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},0)}
export function csvEscape(v){if(v==null||Number.isNaN(v))return'';const s=String(v);return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
export function percentile(sorted,p){if(!sorted.length)return NaN;const i=(sorted.length-1)*p;const lo=Math.floor(i),hi=Math.ceil(i);return lo===hi?sorted[lo]:sorted[lo]+(sorted[hi]-sorted[lo])*(i-lo)}
function finiteMedian(values){const a=values.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return NaN;const mid=Math.floor(a.length/2);return a.length%2?a[mid]:(a[mid-1]+a[mid])/2}
function bridgeSmallGaps(points,key,maxGap=2){const out=points.map(p=>({...p}));const n=out.length;for(let start=0;start<n;start++){if(Number.isFinite(out[start][key]))continue;let end=start;while(end<n&&!Number.isFinite(out[end][key]))end++;const len=end-start;if(len<=maxGap){const left=out[(start-1+n)%n],right=out[end%n];if(Number.isFinite(left[key])&&Number.isFinite(right[key])&&(left.detected||left.confidence>=.45)&&(right.detected||right.confidence>=.45)){for(let k=0;k<len;k++){const t=(k+1)/(len+1);out[start+k][key]=left[key]+(right[key]-left[key])*t;out[start+k].uncertain=true;out[start+k].interpolated=true;out[start+k].confidence=Math.min(out[start+k].confidence||0,.35)}}}start=end}return out}
export function circularRobustSmooth(points,key,radius,{gap=2}={}){if(radius<=0)return points.map(p=>({...p}));const n=points.length;const bridged=bridgeSmallGaps(points,key,gap);const med=bridged.map((p,i)=>{const q={...p};const vals=[];for(let k=-radius;k<=radius;k++)vals.push(bridged[(i+k+n)%n][key]);const m=finiteMedian(vals);q[key]=Number.isFinite(m)?m:p[key];return q});return med.map((p,i)=>{const q={...p};let sum=0,w=0;for(let k=-radius;k<=radius;k++){const r=med[(i+k+n)%n];const val=r[key];if(Number.isFinite(val)){const wt=radius+1-Math.abs(k);sum+=val*wt;w+=wt}}q[key]=w?sum/w:p[key];return q})}
